name: Health Check

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-health:
    runs-on: ubuntu-latest

    steps:
      - name: Make GET request to health-check endpoint
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" https://careerhub-app.onrender.com/api/auth/health-check/)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "Health check failed with status code $RESPONSE"
            exit 1
          else
            echo "Service is running with status $RESPONSE"
          fi
